### ISSUE TITLE
Using sudo for Brew?

### ISSUE THREAD

**Issue by christopheranderton** [ubaltaci/simple-exiftool#1]
Noticed that `sudo` is used in the description for installing the Homebrew packages. Is it just a quick misswrite? As `sudo brew` is only used when you have changed the owner of brew to root for some reason.

Cheers!

**Comment by ubaltaci** [comment]
Hi @christopheranderton, thank you :) updated with 57c8935d129645dac796ac426d07ee8a702ab264
